### PR TITLE
add parallel processing with the ```future.apply```

### PR DESCRIPTION
**Pull request by seonghobae**
Hello there!

I added a parallel processing feature with the ```future.apply``` library.

This patch is harmless to everyone, and make a foundation of who want to use this ```textrank``` library in the high-performance computing environment.
Please checkout my request, and I hope my commitment will be accepted.

Best,
Seongho

### CODE REVIEW

**Review by jwijffels — COMMENTED** [review]
Thanks. Can you make the future.apply package a suggest package instead.

**Comment by seonghobae** [comment]
I already added to import in the namespace and description file; however, are you meant to move into the 'suggest' not in 'import'?

**Comment by jwijffels** [comment]
Yes

**Comment by seonghobae** [comment]
Okay, I'm modifying that now!

**Comment by seonghobae** [comment]
I made a push into the GitHub!

**Review by jwijffels — COMMENTED** [review]
Just use requirenamespace instead of installed.packages

**Comment by seonghobae** [comment]
Okay, If I replace that, R warns like this in code testing procedures; however, I'm making a fix right now if you never minded.

```R
N  checking R code for possible problems (5.4s)
   textrank_candidates_all: no visible global function definition for
     ‘installed.packages’
   textrank_candidates_lsh: no visible global function definition for
     ‘installed.packages’
   textrank_keywords: no visible global function definition for
     ‘installed.packages’
   textrank_sentences: no visible global function definition for
     ‘installed.packages’
   Undefined global functions or variables:
     installed.packages
   Consider adding
     importFrom("utils", "installed.packages")
   to your NAMESPACE file.
```

**Comment by seonghobae** [comment]
Okay, all issues solved.

**Comment by jwijffels** [comment]
I meant as in https://github.com/bnosac/udpipe/blob/9ef8434a6394538ddbd298df0922cb4f9a03399a/R/topicmodels.R#L71

**Comment by jwijffels** [comment]
I meant as in https://github.com/bnosac/udpipe/blob/9ef8434a6394538ddbd298df0922cb4f9a03399a/R/topicmodels.R#L71 like if(requireNamespace("future.apply"))

**Comment by seonghobae** [comment]
Sorry, I miss understood what you said. I make a fix now.

**Pull request closed without merging**
